// components/home/projects.tsx
import { getAllProjects } from "@/lib/server/projects";
import ProjectCard from "../ui/project-card";
import Link from "next/link";
import { getTranslations } from "next-intl/server";

export default async function Projects() {
    const { data } = await getAllProjects({ take: 3, isActive: true });
    const t = await getTranslations("home_projects");
    return (
        <section id="projects" className="px-4 py-24">
            <h2 className="mb-12 text-center font-mono text-2xl font-bold text-text md:text-3xl">{t("title")}</h2>
            <ProjectCard projects={data?.projects ?? []} />
            <div className="mt-10 text-center">
                <Link
                    href="/projects"
                    className="font-mono text-s text-accent-foreground transition-colors duration-150 hover:underline"
                >
                    {t("see_all")}
                </Link>
            </div>
        </section>
    );
}

// src/lib/components/Projects.svelte
<script lang="ts">
	import type { Project } from '@prisma/client';
	import * as m from '$lib/paraglide/messages';
	import { localizeHref } from '$lib/paraglide/runtime';
	import ProjectCard from './ProjectCard.svelte';

	let { projects }: { projects: Project[] } = $props();
</script>

<section id="projects" class="py-24">
	<h2 class="mb-12 text-center font-mono text-2xl font-bold text-text md:text-3xl">
		{m.section_projects()}
	</h2>

	<div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
		{#each projects as project (project.id)}
			<ProjectCard {project} />
		{/each}
	</div>

	<div class="mt-10 text-center">
		<a
			href={localizeHref('/projects')}
			class="font-mono text-sm text-accent transition-colors duration-150 hover:underline"
		>
			{m.projects_view_all()}
		</a>
	</div>
</section>
